# Config file for automatic testing at travis-ci.org

branches:
    except:
        - gh-pages

language: python

python: 2.7

env:
  - TOXENV=py34
  - TOXENV=py33
  - TOXENV=py32

install:
    - pip install tox

script:
    - tox -e $TOX_ENV
