# Config file for automatic testing at travis-ci.org

branches:
    except:
        - gh-pages

language: python

python: 3.4

env:
    - TOXENV=py34
    - TOXENV=py33

install:
    - pip install tox
    - pip install coveralls

script:
    - tox -e $TOXENV

after_success:
    - coveralls
